
name: sorteios-campanha
description: Aplicativo de gerenciamento de campanha de sorteio
icon: https://cdn-icons-png.flaticon.com/512/1402/1402120.png

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080
    environment:
      NODE_ENV: production
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    proxy:
      port: 8080
      secure: true
