
name: sorteios-campanha
services:
  app:
    image: node:20-alpine
    build:
      context: https://github.com/seu-usuario/sorteios-campanha.git
      dockerfile: |
        FROM node:20-alpine AS builder
        WORKDIR /app
        COPY package*.json ./
        RUN npm ci
        COPY . .
        RUN npm run build
        
        FROM node:20-alpine AS runner
        WORKDIR /app
        RUN npm install -g serve
        COPY --from=builder /app/dist ./dist
        ENV NODE_ENV=production
        ENV PORT=8080
        EXPOSE 8080
        HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
          CMD wget -q --spider http://localhost:8080/ || exit 1
        CMD ["serve", "-s", "dist", "-l", "8080"]
    ports:
      - 8080
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    proxy:
      port: 8080
      secure: true
      domain: ${DOMAIN}
    resources:
      memory: 512
    restart: always
