
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yptfvkurwnuidqhxhrej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdGZ2a3Vyd251aWRxaHhocmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODE3MDMsImV4cCI6MjA2MzA1NzcwM30.BScDJiaG9KLt1QlW4_fdmX9z1MJC9ScX0p1i_th3N-I";

// Define the database schema types
export type ParticipanteType = {
  id: string;
  documento: string;
  nome: string | null;
  email: string | null;
  telefone: string | null;
  rua: string | null;
  numero: string | null;
  bairro: string | null;
  cidade: string | null;
  complemento: string | null;
  cep: string | null;
  uf: string | null;
  senha: string | null;
  genero: string | null;
  data_cadastro: string | null;
};

export type NumeroSorteType = {
  id: string;
  numero: number;
  documento: string | null;
  created_at: string | null;
  obs: string | null;
};

export type ConfiguracaoCampanhaType = {
  id: string;
  series_numericas: number;
  created_at: string | null;
  updated_at: string | null;
};

export type NumerosCadaParticipanteType = {
  id: string | null;
  nome: string | null;
  documento: string | null;
  email: string | null;
  telefone: string | null;
  rua: string | null;
  numero: string | null;
  cidade: string | null;
  complemento: string | null;
  cep: string | null;
  uf: string | null;
  senha: string | null;
  numeros_sorte: number[] | null;
  quantidade_numeros: number | null;
};

// Enhanced database type definition
type EnhancedDatabase = Database & {
  public: {
    Tables: {
      participantes: {
        Row: ParticipanteType;
      };
      numeros_sorte: {
        Row: NumeroSorteType;
      };
      configuracao_campanha: {
        Row: ConfiguracaoCampanhaType;
      };
    };
    Views: {
      numeros_cada_participante: {
        Row: NumerosCadaParticipanteType;
      };
    };
  };
};

// Create Supabase client with enhanced typing
export const supabase = createClient<EnhancedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
