// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yptfvkurwnuidqhxhrej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdGZ2a3Vyd251aWRxaHhocmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODE3MDMsImV4cCI6MjA2MzA1NzcwM30.BScDJiaG9KLt1QlW4_fdmX9z1MJC9ScX0p1i_th3N-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);